### ISSUE TITLE
Crash related to wireless lever from random things

### ISSUE THREAD

**Issue by Huene** [TPPIDev/TestPackPleaseIgnore2#276]
Tail of crashlog, full log found here: http://sprunge.us/cbaK

[17:35:56] [Server thread/ERROR] [FML]: 22: ASM: vazkii.botania.common.block.BlockPistonRelay@3940a905 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[17:35:56] [Server thread/ERROR] [FML]: 23: ASM: lumien.randomthings.Handler.RTTickHandler@526ec6a1 tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[17:35:56] [Server thread/ERROR] [FML]: 24: ASM: appeng.hooks.TickHandler@24b59224 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[17:35:56] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922) ~[?:1.7.0_65]
        at java.util.HashMap$KeyIterator.next(HashMap.java:956) ~[?:1.7.0_65]
        at lumien.randomthings.TileEntities.TileEntityWirelessLever.isPowered(TileEntityWirelessLever.java:125) ~[TileEntityWirelessLever.class:?]
        at lumien.randomthings.Handler.CoreHandler.isBlockIndirectlyGettingPowered(CoreHandler.java:33) ~[CoreHandler.class:?]
        at net.minecraft.world.World.func_72864_z(World.java) ~[ahb.class:?]
        at cofh.thermaldynamics.duct.attachments.ConnectionBase.onNeighborChange(ConnectionBase.java:113) ~[ConnectionBase.class:?]
        at cofh.thermaldynamics.duct.attachments.servo.ServoBase.onNeighborChange(ServoBase.java:109) ~[ServoBase.class:?]
        at cofh.thermaldynamics.duct.attachments.servo.ServoItem.onNeighborChange(ServoItem.java:363) ~[ServoItem.class:?]
        at cofh.thermaldynamics.block.TileTDBase.handleSideUpdate(TileTDBase.java:354) ~[TileTDBase.class:?]
        at cofh.thermaldynamics.block.TileTDBase.onNeighborBlockChange(TileTDBase.java:324) ~[TileTDBase.class:?]
        at cofh.thermaldynamics.block.TileTDBase.checkForChunkUnload(TileTDBase.java:432) ~[TileTDBase.class:?]
        at cofh.thermaldynamics.block.TileTDBase.tickPass(TileTDBase.java:598) ~[TileTDBase.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.tickPass(TileItemDuct.java:193) ~[TileItemDuct.class:?]
        at cofh.thermaldynamics.duct.item.ItemGrid.tickGrid(ItemGrid.java:39) ~[ItemGrid.class:?]
        at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:62) ~[WorldGridList.class:?]
        at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:85) ~[TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_873_TickHandler_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:35:56] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/./crash-reports/crash-2015-04-08_17.35.56-server.txt
[17:35:56] [Server thread/INFO]: Stopping server
[17:35:56] [Server thread/INFO]: Saving players
[17:35:56] [Server thread/INFO]: Saving worlds
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/The End
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Underdark
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Soul Network Dimension
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Spirit World
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Torment
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/The Outer Lands
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Bedrock
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/Twilight Forest
[17:35:56] [Server thread/INFO]: Saving chunks for level 'world'/SpectreWorld
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension 0
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension -1
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension 1
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension -100
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension 42
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension -37
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension -38
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension -42
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension -19
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension 7
[17:35:58] [Server thread/INFO] [FML]: Unloading dimension 2
[17:35:58] [Server thread/INFO] [FML]: Applying holder lookups
[17:35:58] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[17:35:58] [Server thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[17:35:58] [Server thread/INFO] [FML]: Holder lookups applied
[17:35:58] [pool-4-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to /home/minecraft/./world/enderio/dimensionalTransceiver.json
[17:35:58] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by tterrag1098** [comment]
Woah, that's odd. I wonder if TD is threading their duct code.

**Comment by Huene** [comment]
with TD kept in mind, I know which lever it was and the cause was attaching the wireless lever to an itemduct with a servo on it
