### ISSUE TITLE
/ores command failed

### ISSUE THREAD

**Issue by Blackcatz1911** [TPPIDev/TestPackPleaseIgnore2#303]
```
[12:57:05] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[12:57:05] [Server thread/WARN] [ServerTools-PERMISSION]: Couldn't process command
java.lang.NullPointerException
        at tppitweaks.command.CommandOres.processVanillaBookCommand(CommandOres.java:71) ~[CommandOres.class:?]
        at tppitweaks.command.CommandOres.func_71515_b(CommandOres.java:48) ~[CommandOres.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:74) [z.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
This is the answer when I try to run the command `/ores`
Using latest TPPI2 build.

**Comment by TehNut** [comment]
>ServerTools-PERMISSION

@matthewprenger Thoughts?

**Comment by matthewprenger** [comment]
ServerTools-Permission takes over execution of commands, that's why its logger is used. Looks like a nullpointer in the TPPITweaks command is causing it though.

**Comment by TehNut** [comment]
Going to assume this was a one-off issue.
